import type { PipelineDocumentViewModel } from './types.ts'

const blankDocument: PipelineDocumentViewModel = {
  id: 'blank-workspace',
  title: 'Blank workspace',
  subtitle: 'Use this as the shell target before file-open and parse commands are wired.',
  sourceKind: 'sample',
  sourceLabel: 'Canvas shell only',
  parserStatus: 'empty',
  normalizedText: 'Paste or open a pipeline to populate the graph.',
  normalizedTextPreview: 'Paste or open a pipeline to populate the graph.',
  diagnostics: [
    {
      id: 'blank-awaiting-input',
      severity: 'info',
      message: 'No pipeline loaded yet. The workspace is ready to receive graph IR from the backend.',
    },
  ],
  graph: {
    nodes: [],
    edges: [],
  },
}

const pipmuxDocument: PipelineDocumentViewModel = {
  id: 'sample-27-pipmux',
  title: '27_pipmux',
  subtitle: 'Dual EO and IR branches converge into composition, detection, and transport outputs.',
  sourceKind: 'sample',
  sourceLabel: '27_pipmux.pld.rtf',
  parserStatus: 'parsed',
  normalizedText:
    'qtiqmmfsrc name=eocam0 ! tee name=eoraw ! ... output-selector name=eo_sr_in ... qtivcomposer name=mixer',
  normalizedTextPreview:
    'qtiqmmfsrc name=eocam0 ! tee name=eoraw ! ... output-selector name=eo_sr_in ... qtivcomposer name=mixer',
  diagnostics: [
    {
      id: 'pipmux-request-pad',
      severity: 'warning',
      nodeId: 'mixer',
      message: 'Request-pad link "mixer.sink_1" is preserved as a labeled edge until backend port modeling lands.',
    },
    {
      id: 'pipmux-placeholder',
      severity: 'info',
      nodeId: 'tracks',
      message: 'Vendor placeholders such as {IR_BITRATE} and {VENC_CODEC} are treated as opaque text.',
    },
    {
      id: 'pipmux-named-ref',
      severity: 'warning',
      nodeId: 'eismux',
      message: 'Named reference "eoraw." is carried through as a branch marker rather than a hard failure.',
    },
  ],
  graph: {
    nodes: [
      {
        id: 'eocam0',
        factoryName: 'qtiqmmfsrc',
        instanceName: 'eocam0',
        kind: 'element',
        tone: 'source',
        description: 'Primary EO camera source and the start of the top branch.',
        tags: ['EO', 'camera', 'source'],
        warnings: [],
        properties: [{ key: 'camera', value: '0' }],
        position: { x: 40, y: 90 },
        sourceSpan: { lineStart: 1, lineEnd: 1 },
      },
      {
        id: 'eoraw',
        factoryName: 'tee',
        instanceName: 'eoraw',
        kind: 'virtual_group',
        tone: 'branch',
        description: 'EO branch split feeding EIS, SR selection, and side-channel outputs.',
        tags: ['EO', 'tee', 'branch'],
        warnings: ['Named link eoraw. fans out into multiple downstream statements.'],
        properties: [],
        position: { x: 250, y: 90 },
        sourceSpan: { lineStart: 2, lineEnd: 2 },
      },
      {
        id: 'eismux',
        factoryName: 'qtimetamux',
        instanceName: 'eismux',
        kind: 'element',
        tone: 'merge',
        description: 'EIS metadata merge point receiving optical-flow side data.',
        tags: ['EO', 'EIS', 'merge'],
        warnings: ['Optical-flow side path is represented as a labeled merge edge only.'],
        properties: [{ key: 'mode', value: '1' }],
        position: { x: 490, y: 30 },
        sourceSpan: { lineStart: 2, lineEnd: 3 },
      },
      {
        id: 'eo_sr_in',
        factoryName: 'output-selector',
        instanceName: 'eo_sr_in',
        kind: 'element',
        tone: 'branch',
        description: 'EO super-resolution selector switching among enhancement branches.',
        tags: ['EO', 'selector'],
        warnings: [],
        properties: [{ key: 'active-pad', value: 'eo_sr_in.src_0' }],
        position: { x: 760, y: 90 },
        sourceSpan: { lineStart: 9, lineEnd: 9 },
      },
      {
        id: 'eo_sr_out',
        factoryName: 'funnel',
        instanceName: 'eo_sr_out',
        kind: 'element',
        tone: 'merge',
        description: 'EO merge point for the selector outputs before overlay and encoding.',
        tags: ['EO', 'merge'],
        warnings: [],
        properties: [{ key: 'forward-sticky-events', value: '0' }],
        position: { x: 1030, y: 90 },
        sourceSpan: { lineStart: 30, lineEnd: 31 },
      },
      {
        id: 'eo_det_hd',
        factoryName: 'tee',
        instanceName: 'eo_det_hd',
        kind: 'virtual_group',
        tone: 'branch',
        description: 'EO high-definition branch split for overlay and detection.',
        tags: ['EO', 'detection'],
        warnings: [],
        properties: [],
        position: { x: 1260, y: 90 },
        sourceSpan: { lineStart: 32, lineEnd: 33 },
      },
      {
        id: 'eometamux',
        factoryName: 'qtimetamux',
        instanceName: 'eometamux',
        kind: 'element',
        tone: 'merge',
        description: 'EO detection metadata funnel feeding the tracker branch.',
        tags: ['EO', 'detection', 'metadata'],
        warnings: [],
        properties: [{ key: 'mode', value: '2' }],
        position: { x: 1510, y: 190 },
        sourceSpan: { lineStart: 36, lineEnd: 40 },
      },
      {
        id: 'ircam0',
        factoryName: 'v4l2src',
        instanceName: 'ircam0',
        kind: 'element',
        tone: 'source',
        description: 'IR camera source establishing the lower branch.',
        tags: ['IR', 'camera', 'source'],
        warnings: [],
        properties: [{ key: 'device', value: '/dev/video2' }],
        position: { x: 40, y: 360 },
        sourceSpan: { lineStart: 41, lineEnd: 41 },
      },
      {
        id: 'irraw',
        factoryName: 'tee',
        instanceName: 'irraw',
        kind: 'virtual_group',
        tone: 'branch',
        description: 'IR branch split feeding recording, SR, and detection paths.',
        tags: ['IR', 'tee', 'branch'],
        warnings: [],
        properties: [],
        position: { x: 250, y: 360 },
        sourceSpan: { lineStart: 42, lineEnd: 42 },
      },
      {
        id: 'ir_sr_in',
        factoryName: 'output-selector',
        instanceName: 'ir_sr_in',
        kind: 'element',
        tone: 'branch',
        description: 'IR selector for multiple super-resolution crop paths.',
        tags: ['IR', 'selector'],
        warnings: [],
        properties: [{ key: 'active-pad', value: 'ir_sr_in.src_0' }],
        position: { x: 760, y: 360 },
        sourceSpan: { lineStart: 42, lineEnd: 42 },
      },
      {
        id: 'ir_sr_out',
        factoryName: 'funnel',
        instanceName: 'ir_sr_out',
        kind: 'element',
        tone: 'merge',
        description: 'IR merge point before HUD overlay, encoding, and composition.',
        tags: ['IR', 'merge'],
        warnings: [],
        properties: [{ key: 'forward-sticky-events', value: '0' }],
        position: { x: 1030, y: 360 },
        sourceSpan: { lineStart: 73, lineEnd: 74 },
      },
      {
        id: 'ir_det_hd',
        factoryName: 'tee',
        instanceName: 'ir_det_hd',
        kind: 'virtual_group',
        tone: 'branch',
        description: 'IR high-definition branch split for overlay and detection.',
        tags: ['IR', 'detection'],
        warnings: [],
        properties: [],
        position: { x: 1260, y: 360 },
        sourceSpan: { lineStart: 75, lineEnd: 76 },
      },
      {
        id: 'irmetamux',
        factoryName: 'qtimetamux',
        instanceName: 'irmetamux',
        kind: 'element',
        tone: 'merge',
        description: 'IR detection metadata aggregator feeding tracker output.',
        tags: ['IR', 'detection', 'metadata'],
        warnings: [],
        properties: [{ key: 'mode', value: '2' }],
        position: { x: 1510, y: 460 },
        sourceSpan: { lineStart: 82, lineEnd: 86 },
      },
      {
        id: 'tracks',
        factoryName: 'svtracker',
        instanceName: 'tracks',
        kind: 'element',
        tone: 'ai',
        description: 'Merged EO and IR detections are tracked into a target-info stream.',
        tags: ['tracker', 'detection', 'fusion'],
        warnings: ['Tracker configuration placeholders remain opaque until semantic enrichment exists.'],
        properties: [{ key: 'algo', value: '{MOT_MODE}' }],
        position: { x: 1760, y: 320 },
        sourceSpan: { lineStart: 87, lineEnd: 88 },
      },
      {
        id: 'mixer',
        factoryName: 'qtivcomposer',
        instanceName: 'mixer',
        kind: 'element',
        tone: 'merge',
        description: 'Canvas composition node that joins EO primary output with IR picture-in-picture.',
        tags: ['compose', 'output', 'merge'],
        warnings: ['Request pad metadata is shown as edge labels for now.'],
        properties: [{ key: 'sink_1::dimensions', value: '<320, 180>' }],
        position: { x: 1760, y: 110 },
        sourceSpan: { lineStart: 90, lineEnd: 91 },
      },
      {
        id: 'eo_venc',
        factoryName: 'qtic2venc',
        instanceName: 'eo_venc',
        kind: 'element',
        tone: 'output',
        description: 'Final EO transport encoder after composition.',
        tags: ['encode', 'transport'],
        warnings: ['Codec placeholder stays unresolved until runtime configuration is known.'],
        properties: [{ key: 'target-bitrate', value: '{EO_BITRATE}' }],
        position: { x: 2010, y: 110 },
        sourceSpan: { lineStart: 92, lineEnd: 94 },
      },
    ],
    edges: [
      { id: 'eocam0-eoraw', sourceNodeId: 'eocam0', targetNodeId: 'eoraw', label: 'video/x-raw(memory:GBM)' },
      { id: 'eoraw-eismux', sourceNodeId: 'eoraw', targetNodeId: 'eismux', label: 'named ref: eoraw.' },
      { id: 'eismux-eo-sr-in', sourceNodeId: 'eismux', targetNodeId: 'eo_sr_in', label: 'NV12 1280x720' },
      { id: 'eo-sr-in-out', sourceNodeId: 'eo_sr_in', targetNodeId: 'eo_sr_out', label: 'active-pad src_0' },
      { id: 'eo-sr-out-det', sourceNodeId: 'eo_sr_out', targetNodeId: 'eo_det_hd', label: 'merged EO' },
      { id: 'eo-det-meta', sourceNodeId: 'eo_det_hd', targetNodeId: 'eometamux', label: 'detection side branch' },
      { id: 'ircam0-irraw', sourceNodeId: 'ircam0', targetNodeId: 'irraw', label: 'video/x-raw' },
      { id: 'irraw-sr-in', sourceNodeId: 'irraw', targetNodeId: 'ir_sr_in', label: 'crop + selector' },
      { id: 'ir-sr-in-out', sourceNodeId: 'ir_sr_in', targetNodeId: 'ir_sr_out', label: 'active-pad src_0' },
      { id: 'ir-sr-out-det', sourceNodeId: 'ir_sr_out', targetNodeId: 'ir_det_hd', label: 'merged IR' },
      { id: 'ir-det-meta', sourceNodeId: 'ir_det_hd', targetNodeId: 'irmetamux', label: 'detection side branch' },
      { id: 'eo-meta-tracks', sourceNodeId: 'eometamux', targetNodeId: 'tracks', label: 'detections.' },
      { id: 'ir-meta-tracks', sourceNodeId: 'irmetamux', targetNodeId: 'tracks', label: 'detections.' },
      { id: 'eo-to-mixer', sourceNodeId: 'eo_det_hd', targetNodeId: 'mixer', label: 'mixer.sink_0' },
      { id: 'ir-to-mixer', sourceNodeId: 'ir_det_hd', targetNodeId: 'mixer', label: 'mixer.sink_1' },
      { id: 'mixer-encoder', sourceNodeId: 'mixer', targetNodeId: 'eo_venc', label: 'NV12 composed output' },
    ],
  },
}

const smoothingDocument: PipelineDocumentViewModel = {
  id: 'sample-26-release-record-smoothing',
  title: '26_release_record_smoothing',
  subtitle: 'EO and IR capture branches prioritize recording and transport alongside analysis paths.',
  sourceKind: 'sample',
  sourceLabel: '26_release_record_smoothing.pld.rtf',
  parserStatus: 'parsed',
  normalizedText:
    'qtiqmmfsrc camera=0 name=eocam0 ! tee name=eoraw ! ... qtivcomposer name=mixer',
  normalizedTextPreview:
    'qtiqmmfsrc name=eocam0 ! tee name=eoraw ! ... splitmuxsink name=tsrec_eo ... tee name=eoenc',
  diagnostics: [
    {
      id: 'smoothing-recording',
      severity: 'warning',
      nodeId: 'tsrec_eo',
      message: 'Subtitle request pads for splitmuxsink are represented as abstract outputs in the placeholder graph.',
    },
    {
      id: 'smoothing-opaque-codec',
      severity: 'info',
      nodeId: 'eo_venc',
      message: 'Codec-specific parse/pay elements stay collapsed into a single output segment for now.',
    },
  ],
  graph: {
    nodes: [
      {
        id: 'smoothing-eocam0',
        factoryName: 'qtiqmmfsrc',
        instanceName: 'eocam0',
        kind: 'element',
        tone: 'source',
        description: 'EO camera feed for the recording-oriented sample.',
        tags: ['EO', 'source'],
        warnings: [],
        properties: [{ key: 'camera', value: '0' }],
        position: { x: 40, y: 80 },
        sourceSpan: { lineStart: 1, lineEnd: 1 },
      },
      {
        id: 'smoothing-eoraw',
        factoryName: 'tee',
        instanceName: 'eoraw',
        kind: 'virtual_group',
        tone: 'branch',
        description: 'EO split branching to recording, EIS, and SR selection.',
        tags: ['EO', 'tee'],
        warnings: ['Side recording path is compressed into a single branch summary.'],
        properties: [],
        position: { x: 250, y: 80 },
        sourceSpan: { lineStart: 2, lineEnd: 2 },
      },
      {
        id: 'smoothing-tsrec-eo',
        factoryName: 'splitmuxsink',
        instanceName: 'tsrec_eo',
        kind: 'element',
        tone: 'output',
        description: 'EO inbound recording sink for time-sliced transport stream capture.',
        tags: ['recording', 'output'],
        warnings: ['Associated subtitle pad appsrc is not expanded into the graph yet.'],
        properties: [{ key: 'location', value: '/tmp/EO_IN_%d.ts' }],
        position: { x: 560, y: 10 },
        sourceSpan: { lineStart: 18, lineEnd: 22 },
      },
      {
        id: 'smoothing-eo-sr-in',
        factoryName: 'output-selector',
        instanceName: 'eo_sr_in',
        kind: 'element',
        tone: 'branch',
        description: 'EO SR selector preserving the same family of enhancement branches.',
        tags: ['EO', 'selector'],
        warnings: [],
        properties: [{ key: 'active-pad', value: 'eo_sr_in.src_0' }],
        position: { x: 560, y: 140 },
        sourceSpan: { lineStart: 9, lineEnd: 9 },
      },
      {
        id: 'smoothing-eo-sr-out',
        factoryName: 'funnel',
        instanceName: 'eo_sr_out',
        kind: 'element',
        tone: 'merge',
        description: 'EO merge point before overlay, encoding, and branching to streaming plus archive outputs.',
        tags: ['EO', 'merge'],
        warnings: [],
        properties: [{ key: 'forward-sticky-events', value: '0' }],
        position: { x: 830, y: 140 },
        sourceSpan: { lineStart: 30, lineEnd: 31 },
      },
      {
        id: 'smoothing-eoenc',
        factoryName: 'tee',
        instanceName: 'eoenc',
        kind: 'virtual_group',
        tone: 'branch',
        description: 'Encoded EO stream split between RTP transport and local archive.',
        tags: ['EO', 'encode', 'branch'],
        warnings: [],
        properties: [],
        position: { x: 1110, y: 140 },
        sourceSpan: { lineStart: 35, lineEnd: 37 },
      },
      {
        id: 'smoothing-eo-out-mux',
        factoryName: 'splitmuxsink',
        instanceName: 'EO_OUT_MUX',
        kind: 'element',
        tone: 'output',
        description: 'Post-encode EO archive sink writing Matroska segments.',
        tags: ['archive', 'output'],
        warnings: [],
        properties: [{ key: 'location', value: '/tmp/EO_OUT_%d.mkv' }],
        position: { x: 1380, y: 60 },
        sourceSpan: { lineStart: 37, lineEnd: 37 },
      },
      {
        id: 'smoothing-ircam0',
        factoryName: 'v4l2src',
        instanceName: 'ircam0',
        kind: 'element',
        tone: 'source',
        description: 'IR camera source mirrored from the EO pipeline.',
        tags: ['IR', 'source'],
        warnings: [],
        properties: [{ key: 'device', value: '/dev/video2' }],
        position: { x: 40, y: 360 },
        sourceSpan: { lineStart: 41, lineEnd: 41 },
      },
      {
        id: 'smoothing-irraw',
        factoryName: 'tee',
        instanceName: 'irraw',
        kind: 'virtual_group',
        tone: 'branch',
        description: 'IR split routing to recording, SR, and downstream encoder output.',
        tags: ['IR', 'tee'],
        warnings: [],
        properties: [],
        position: { x: 250, y: 360 },
        sourceSpan: { lineStart: 42, lineEnd: 42 },
      },
      {
        id: 'smoothing-tsrec-ir',
        factoryName: 'splitmuxsink',
        instanceName: 'tsrec_ir',
        kind: 'element',
        tone: 'output',
        description: 'IR inbound recording sink for transport stream capture.',
        tags: ['recording', 'output'],
        warnings: [],
        properties: [{ key: 'location', value: '/tmp/IR_IN_%d.ts' }],
        position: { x: 560, y: 290 },
        sourceSpan: { lineStart: 49, lineEnd: 54 },
      },
      {
        id: 'smoothing-ir-sr-in',
        factoryName: 'output-selector',
        instanceName: 'ir_sr_in',
        kind: 'element',
        tone: 'branch',
        description: 'IR selector for full-frame and cropped SR options.',
        tags: ['IR', 'selector'],
        warnings: [],
        properties: [{ key: 'active-pad', value: 'ir_sr_in.src_0' }],
        position: { x: 560, y: 420 },
        sourceSpan: { lineStart: 42, lineEnd: 42 },
      },
      {
        id: 'smoothing-ir-sr-out',
        factoryName: 'funnel',
        instanceName: 'ir_sr_out',
        kind: 'element',
        tone: 'merge',
        description: 'IR merge point before encoder and archive split.',
        tags: ['IR', 'merge'],
        warnings: [],
        properties: [{ key: 'forward-sticky-events', value: '0' }],
        position: { x: 830, y: 420 },
        sourceSpan: { lineStart: 73, lineEnd: 74 },
      },
      {
        id: 'smoothing-irenc',
        factoryName: 'tee',
        instanceName: 'irenc',
        kind: 'virtual_group',
        tone: 'branch',
        description: 'Encoded IR stream split between RTP output and local archive.',
        tags: ['IR', 'encode', 'branch'],
        warnings: [],
        properties: [],
        position: { x: 1110, y: 420 },
        sourceSpan: { lineStart: 78, lineEnd: 80 },
      },
      {
        id: 'smoothing-ir-out-mux',
        factoryName: 'splitmuxsink',
        instanceName: 'IR_OUT_MUX',
        kind: 'element',
        tone: 'output',
        description: 'Post-encode IR archive sink writing Matroska segments.',
        tags: ['archive', 'output'],
        warnings: [],
        properties: [{ key: 'location', value: '/tmp/IR_OUT_%d.mkv' }],
        position: { x: 1380, y: 340 },
        sourceSpan: { lineStart: 80, lineEnd: 80 },
      },
    ],
    edges: [
      { id: 'smooth-eo-source', sourceNodeId: 'smoothing-eocam0', targetNodeId: 'smoothing-eoraw', label: 'video/x-raw(memory:GBM)' },
      { id: 'smooth-eo-record', sourceNodeId: 'smoothing-eoraw', targetNodeId: 'smoothing-tsrec-eo', label: 'EO_IN recording branch' },
      { id: 'smooth-eo-selector', sourceNodeId: 'smoothing-eoraw', targetNodeId: 'smoothing-eo-sr-in', label: 'SR selection branch' },
      { id: 'smooth-eo-merge', sourceNodeId: 'smoothing-eo-sr-in', targetNodeId: 'smoothing-eo-sr-out', label: 'selected EO branch' },
      { id: 'smooth-eo-encode', sourceNodeId: 'smoothing-eo-sr-out', targetNodeId: 'smoothing-eoenc', label: 'encoded EO output' },
      { id: 'smooth-eo-archive', sourceNodeId: 'smoothing-eoenc', targetNodeId: 'smoothing-eo-out-mux', label: 'EO_OUT archive' },
      { id: 'smooth-ir-source', sourceNodeId: 'smoothing-ircam0', targetNodeId: 'smoothing-irraw', label: 'video/x-raw' },
      { id: 'smooth-ir-record', sourceNodeId: 'smoothing-irraw', targetNodeId: 'smoothing-tsrec-ir', label: 'IR_IN recording branch' },
      { id: 'smooth-ir-selector', sourceNodeId: 'smoothing-irraw', targetNodeId: 'smoothing-ir-sr-in', label: 'SR selection branch' },
      { id: 'smooth-ir-merge', sourceNodeId: 'smoothing-ir-sr-in', targetNodeId: 'smoothing-ir-sr-out', label: 'selected IR branch' },
      { id: 'smooth-ir-encode', sourceNodeId: 'smoothing-ir-sr-out', targetNodeId: 'smoothing-irenc', label: 'encoded IR output' },
      { id: 'smooth-ir-archive', sourceNodeId: 'smoothing-irenc', targetNodeId: 'smoothing-ir-out-mux', label: 'IR_OUT archive' },
    ],
  },
}

const sampleDocuments = [pipmuxDocument, smoothingDocument]

export { blankDocument, sampleDocuments }
